#!/bin/sh

# Script based on Peroni
UNROLL=-fno-unroll-loops
XCLANG=-Xclang 
LOAD=-load
CAT=~/CAT/lib/CAT.so
ISO=0
QEMU=0
SAVE=0
SAVEDIR=""
TTY=""

for arg in "$@"
do 
	case $arg in 
		-u)
		UNROLL=""
		shift
		;;
		-t)
		XCLANG=""
		LOAD=""
		CAT=""
		shift
		;;
		-i)
		ISO=1
		shift
		;;
		-r=*)
		QEMU=1
		TTY=${arg#*=}
		shift
		;;
		-s=*|-save=*)
		ISO=1
		SAVE=1
		SAVEDIR=${arg#*=}
		shift
		;;
	esac

done

source /project/llvm/8.0.0/enable
export PATH=~/CAT/bin:$PATH

cd ~/CAT-c
./run_me.sh

cd ~/nautilus-cs446
make clean
make V=1 -j 4

clang -emit-llvm -Wp,-MD,src/nautilus/.fiber.o.d   -D__NAUTILUS__ -Iinclude  -include include/autoconf.h -D__NAUTILUS__ -fno-omit-frame-pointer -ffreestanding -fno-stack-protector -fno-strict-aliasing -fno-strict-overflow -mno-red-zone -mcmodel=large -O2 $UNROLL  -Wall -Wno-unused-function -Wno-unused-variable -fno-common -Wstrict-overflow=5 -fgnu89-inline -g -m64  -Wno-pointer-sign    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fiber)"  -D"KBUILD_MODNAME=KBUILD_STR(fiber)" -c -Xclang -disable-O0-optnone -o src/llvm/fiber-injection/test/runtime/fibers/fibers.bc src/test/fibers.c

clang -emit-llvm -Wp,-MD,src/nautilus/.fiber.o.d   -D__NAUTILUS__ -Iinclude  -include include/autoconf.h -D__NAUTILUS__ -fno-omit-frame-pointer -ffreestanding -fno-stack-protector -fno-strict-aliasing -fno-strict-overflow -mno-red-zone -mcmodel=large  -O2 $UNROLL  -Wall -Wno-unused-function -Wno-unused-variable -fno-common -Wstrict-overflow=5 -fgnu89-inline -g -m64  -Wno-pointer-sign    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fiber)"  -D"KBUILD_MODNAME=KBUILD_STR(fiber)" -c -Xclang -disable-O0-optnone -o src/llvm/fiber-injection/test/runtime/instrument/instrument.bc src/test/instrument.c

clang -emit-llvm -Wp,-MD,src/nautilus/.fiber.o.d   -D__NAUTILUS__ -Iinclude  -include include/autoconf.h -D__NAUTILUS__ -fno-omit-frame-pointer -ffreestanding -fno-stack-protector -fno-strict-aliasing -fno-strict-overflow -mno-red-zone -mcmodel=large  -O2 $UNROLL  -Wall -Wno-unused-function -Wno-unused-variable -fno-common -Wstrict-overflow=5 -fgnu89-inline -g -m64  -Wno-pointer-sign    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fiber)"  -D"KBUILD_MODNAME=KBUILD_STR(fiber)" -c -Xclang -disable-O0-optnone -o src/nautilus/fiber.bc src/nautilus/fiber.c

llvm-link -internalize src/llvm/fiber-injection/test/runtime/fibers/fibers.bc src/nautilus/fiber.bc -o src/llvm/fiber-injection/test/runtime/fibers/fibers_link.bc
llvm-dis src/llvm/fiber-injection/test/runtime/fibers/fibers_link.bc

llvm-link -internalize src/llvm/fiber-injection/test/runtime/instrument/instrument.bc src/nautilus/fiber.bc -o src/llvm/fiber-injection/test/runtime/instrument/instrument_link.bc
llvm-dis src/llvm/fiber-injection/test/runtime/instrument/instrument_link.bc

clang -emit-llvm $XCLANG $LOAD $XCLANG $CAT -Wp,-MD,src/nautilus/.fiber.o.d   -D__NAUTILUS__ -Iinclude  -include include/autoconf.h -D__NAUTILUS__ -fno-omit-frame-pointer -ffreestanding -fno-stack-protector -fno-strict-aliasing -fno-strict-overflow -mno-red-zone -mcmodel=large -O0 -loops -Wall -Wno-unused-function -Wno-unused-variable -fno-common -Wstrict-overflow=5 -fgnu89-inline -g -m64  -Wno-pointer-sign    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fiber)"  -D"KBUILD_MODNAME=KBUILD_STR(fiber)" -c -Xclang -disable-O0-optnone -o src/llvm/fiber-injection/test/runtime/fibers/fibers_optimized.bc src/llvm/fiber-injection/test/runtime/fibers/fibers_link.bc &> src/llvm/fiber-injection/test/runtime/fibers/fiber_output
 
clang -Wp,-MD,src/nautilus/.fiber.o.d   -D__NAUTILUS__ -Iinclude  -include include/autoconf.h -D__NAUTILUS__ -fno-omit-frame-pointer -ffreestanding -fno-stack-protector -fno-strict-aliasing -fno-strict-overflow -mno-red-zone -mcmodel=large  -O2 -Wall -Wno-unused-function -Wno-unused-variable -fno-common -Wstrict-overflow=5 -fgnu89-inline -g -m64  -Wno-pointer-sign    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fiber)"  -D"KBUILD_MODNAME=KBUILD_STR(fiber)" -c -o src/llvm/fiber-injection/test/runtime/fibers.o src/llvm/fiber-injection/test/runtime/fibers/fibers_optimized.bc

clang -emit-llvm $XCLANG $LOAD $XCLANG $CAT -Wp,-MD,src/nautilus/.fiber.o.d   -D__NAUTILUS__ -Iinclude  -include include/autoconf.h -D__NAUTILUS__ -fno-omit-frame-pointer -ffreestanding -fno-stack-protector -fno-strict-aliasing -fno-strict-overflow -mno-red-zone -mcmodel=large  -O0 -loops -Wall -Wno-unused-function -Wno-unused-variable -fno-common -Wstrict-overflow=5 -fgnu89-inline -g -m64  -Wno-pointer-sign    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fiber)"  -D"KBUILD_MODNAME=KBUILD_STR(fiber)" -c -Xclang -disable-O0-optnone -o src/llvm/fiber-injection/test/runtime/instrument/instrument_optimized.bc src/llvm/fiber-injection/test/runtime/instrument/instrument_link.bc &> src/llvm/fiber-injection/test/runtime/instrument/instrument_output
 
clang -Wp,-MD,src/nautilus/.fiber.o.d   -D__NAUTILUS__ -Iinclude  -include include/autoconf.h -D__NAUTILUS__ -fno-omit-frame-pointer -ffreestanding -fno-stack-protector -fno-strict-aliasing -fno-strict-overflow -mno-red-zone -mcmodel=large  -O2 -Wall -Wno-unused-function -Wno-unused-variable -fno-common -Wstrict-overflow=5 -fgnu89-inline -g -m64  -Wno-pointer-sign    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(fiber)"  -D"KBUILD_MODNAME=KBUILD_STR(fiber)" -c -o src/llvm/fiber-injection/test/runtime/instrument.o src/llvm/fiber-injection/test/runtime/instrument/instrument_optimized.bc
         
llvm-dis src/llvm/fiber-injection/test/runtime/fibers/fibers.bc   
llvm-dis src/llvm/fiber-injection/test/runtime/fibers/fibers_optimized.bc

llvm-dis src/llvm/fiber-injection/test/runtime/instrument/instrument.bc
llvm-dis src/llvm/fiber-injection/test/runtime/instrument/instrument_optimized.bc

mv src/nautilus/fiber.bc src/llvm/fiber-injection/test/runtime/fibers/fiber.bc
llvm-dis src/llvm/fiber-injection/test/runtime/fibers/fiber.bc

make V=1

if [ $ISO == 1 ]
then
	export PATH=~/tools/bin:$PATH
	make isoimage
fi

if [ $SAVE == 1 ]
then
	if [ -d "$SAVEDIR" ]
	then
		if  [-d "$SAVEDIR/savebuild" ]
		then
			rm -rf "$SAVEDIR/savebuild"
		fi
		mkdir "$SAVEDIR/savebuild"
		cp nautilus.bin "$SAVEDIR/savebuild"
		cp nautilus.iso "$SAVEDIR/savebuild"
		cp -r src/llvm/fiber-injection/test/runtime/fibers "$SAVEDIR/savebuild"
		cp -r src/llvm/fiber-injection/test/runtime/instrument "$SAVEDIR/savebuild"
		cp inject "$SAVEDIR/savebuild"
		cp ../CAT-c/catpass/CatPass.cpp "$SAVEDIR/savebuild"
	else
		echo "ERROR: Save directory not found"
	fi
fi

if [ $QEMU == 1 ]
then
	qemu-system-x86_64 -display curses -smp 2 -m 2048 -vga std -serial /dev/pts/$TTY -cdrom nautilus.iso
fi
